# STM32F103 template – Kconfig fragments
# Board: stm32_min_dev  (Blue Pill STM32F103C8T6)
# Build: cmake -B build -DBOARD=stm32_min_dev . && cmake --build build -j4

CONFIG_GPIO=y
CONFIG_PRINTK=y
CONFIG_SERIAL=y
