version: '3.8'
services:
  dev:
    image: asuracodes/mcu-lab:base
    volumes:
      - ..:/workspace:cached
    environment:
      - PICO_SDK_PATH=/opt/pico-sdk
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    privileged: true
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    tty: true
    stdin_open: true
    command: sleep infinity
